"""change id to uuid

Revision ID: 3e92a62b9b7f
Revises: 
Create Date: 2024-05-17 10:12:25.992325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e92a62b9b7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('user_email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('user_password_hash', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('user_date_added', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint(None, ['user_email'])
        batch_op.drop_column('date_added')
        batch_op.drop_column('email')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('date_added', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_date_added')
        batch_op.drop_column('user_password_hash')
        batch_op.drop_column('user_email')
        batch_op.drop_column('user_name')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
